name: Get Jenkins Build Info

on: [push]

jobs:
  get-build-info:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Jenkins Build Information
        run: |
          curl -u "kolko:${{secrets.JENKINSACCESS}}" "https://services.beta.wincan.com/jenkins/job/Test%20-%20WebHook/lastBuild/api/json" > build_info.json
          cat build_info.json 
