name: "Trigger Jenkins Job"
on:
  push:
    branches: ['main']
jobs:
  run-updater:
    runs-on: windows-latest
    steps:
    - name: REST API with curl
      run: |
        $BRANCH_NAME = "${{ github.ref }}".Split("/")[-1]
        $url = "https://services.beta.wincan.com/jenkins/job/Test%20-%20WebHook/buildWithParameters?token=12345&BranchName=" + $BRANCH_NAME
        curl -X POST $url -u kolko:${{secrets.JENKINSACCESS}} -k            
    - name: Wait for Jenkins Build to Complete
      run: | 
        $JENKINS_BUILD_URL="https://services.beta.wincan.com/jenkins/job/Test%20-%20WebHook/lastBuild/api/json"

        while ($true) {
            Write-Host "przed"
            $response = curl -Uri $JENKINS_BUILD_URL -UseBasicParsing -u kolko:${{secrets.JENKINSACCESS}} -k 
            Write-Host "w środku"
            $buildStatus = $response.Content | ConvertFrom-Json | Select-Object -ExpandProperty building
            Write-Host "po"
            if ($buildStatus -eq $false) {
                Write-Host "Build completed"
                break
            }

            Write-Host "Waiting for build to complete..."
            Start-Sleep -Seconds 10
        }
      
      
