name: "Trigger Jenkins Job"
on:
  push:
    branches: ['main','development']

jobs:
  run-updater:
    runs-on: self-hosted
    steps:
    - name: REST API with curl
      run: |
        curl -X POST https://services.beta.wincan.com/jenkins/view/Automated%20Tests/job/Test%20-%20Mail/buildWithParameters?token=12345 -u kolko:11d5b43f2703fcfb0da9176246f9dff534 -k
