name: "Trigger Jenkins Job"
on:
  push:
    branches: ['main']

jobs:
  run-updater:
    runs-on: self-hosted
    steps:
    - name: REST API with curl
      run: |
        curl -X POST https://services.beta.wincan.com/jenkins/job/st/buildWithParameters?token=12345 -u kolko:${{secrets.JENKINSACCESS}} -k
