name: "Trigger Jenkins Job"
on:
  push:
    branches: ['main']

jobs:
  run-updater:
    runs-on: windows-latest
    steps:
    - name: REST API with curl
      run: |
        $BRANCH_NAME = "${{ github.ref }}".Split("/")[-1]
        curl -X POST https://services.beta.wincan.com/jenkins/job/st/buildWithParameters?token=12345&BranchName=$BRANCH_NAME -u kolko:${{secrets.JENKINSACCESS}} -k        
