name: "Trigger Jenkins Job and Wait"
on:
  push:
    branches: 
    - main
    - development

jobs:
  run-updater:
    runs-on: windows-latest
    steps:
    - name: Trigger Jenkins Job
      run: |
        $env:BRANCH_NAME = "${{ github.ref }}".Split("/")[-1]
        $url = "https://services.beta.wincan.com/jenkins/job/Test%20-%20WebHook/buildWithParameters?token=12345&BranchName=" + $env:BRANCH_NAME
        curl -X POST $url -u kolko:${{secrets.JENKINSACCESS}} -k
        
    - name: Wait for Jenkins to Update PR Status
      run: |
        $prNumber = ${{ github.event.pull_request.number }}
        $repo = "${{ github.repository }}"
        Write-Host "Repository: $repo"
        Write-Host "Pull Request Number: $prNumber"
        $token = "${{ secrets.GITHUB_TOKEN }}"
        $status = $null
        do {
            Start-Sleep -Seconds 30
            $prApiUrl = "https://api.github.com/repos/$repo/pulls/$prNumber"
            Write-Host "PR API URL: $prApiUrl"
            
            $response = Invoke-RestMethod -Headers @{Authorization="Bearer $token"} -Uri $prApiUrl
            $statusesUrl = $response.statuses_url
            Write-Host "Statuses URL: $statusesUrl"
            
            $statusResponse = Invoke-RestMethod -Headers @{Authorization="Bearer $token"} -Uri $statusesUrl
            $status = $statusResponse | Where-Object { $_.context -eq "Jenkins" } | Select-Object -ExpandProperty state
            Write-Host "Current Status: $status"
        } while ($status -eq $null)

        if ($status -ne 'success') {
            Write-Error "Jenkins build failed or status not updated"
            exit 1
        }
