name: "Trigger Jenkins Job - with validation"
on:
  pull_request:
    types:
      - opened

jobs:
  run-updater:
    runs-on: windows-latest
    steps:
    - name: Validate test
      run: |
        $BRANCH_NAME = "${{ github.ref }}".Split("/")[-1]
        $url = "https://services.beta.wincan.com/jenkins/job/st/buildWithParameters?token=12345&BranchName=" + $BRANCH_NAME
        JENKINS_QUEUE_ITEM=$(curl -X POST $url -u kolko:${{secrets.JENKINSACCESS}} -k)
        echo "JENKINS_QUEUE_ITEM=${JENKINS_QUEUE_ITEM}" >> $GITHUB_ENV

