name: "Trigger Jenkins Job and Wait"
on:
  pull_request:
    branches: 
    - main
    - development    

jobs:
  run-updater:
    runs-on: windows-latest
    steps:
    - name: Trigger Jenkins Job
      run: |
        Write-Host "Branch: $env:BRANCH_NAME"
        $env:BRANCH_NAME = "${{ github.head_ref }}"
        $url = "https://services.beta.wincan.com/jenkins/job/Test%20-%20WebHook/buildWithParameters?token=12345&BranchName=" + $env:BRANCH_NAME
        curl -X POST $url -u kolko:${{secrets.JENKINSACCESS}} -k
        
    - name: Wait for Jenkins to Update PR Status
      run: |
        $prNumber = "${{ github.event.pull_request.number }}"
        $repo = "${{ github.repository }}"
        Write-Host "Repository: $repo"
        Write-Host "Pull Request Number: $prNumber"
        $token = "${{ secrets.GITHUB_TOKEN }}"
        $description = $null
        do {
            Start-Sleep -Seconds 1
            $sha="${{ github.event.pull_request.head.sha }}"
            $repostatusUrl ="https://api.github.com/repos/olkokamil/Test/statuses/$sha"
            Write-Host "URL: $repostatusUrl"
            $response = Invoke-RestMethod -Uri $repostatusUrl -Headers @{Authorization="Bearer ${{secrets.GITHUB_TOKEN}}"}
            $description = $response[0].description
            Write-Host "Description URL: $description"
            $prApiUrl = "https://api.github.com/repos/$repo/pulls/$prNumber"
            Write-Host "PR API URL: $prApiUrl"
            
        } while ($description -eq $null)

        if ($description -ne 'success') {
            Write-Error "Jenkins build failed or status not updated"
            exit 1
        }
