on:
  pull_request:
    types:
      - opened

jobs:
  run-updater:
    runs-on: windows-latest
    steps:
    - name: Validate test
      run: |
        curl -X POST https://services.beta.wincan.com/jenkins/job/Test%20-%20WebHook/buildWithParameters?GITHUB_SHA=${{ github.sha }} -u jenkins-triggers:${{secrets.JENKINSACCESS}} -k
